# Generated by Django 2.1.5 on 2020-03-24 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='structuredproject',
            old_name='content',
            new_name='description',
        ),
    ]
