# Generated by Django 2.1.5 on 2020-03-24 13:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20200324_1319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='structuredproject',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 24, 13, 49, 59, 547383), verbose_name='date published'),
        ),
    ]
