# Generated by Django 2.1.5 on 2020-03-24 17:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20200324_1349'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalProjects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('description1', models.TextField()),
                ('project1', models.TextField()),
                ('title1', models.CharField(max_length=200)),
                ('inuse1', models.BooleanField(default=False)),
                ('project2', models.TextField()),
                ('title2', models.CharField(max_length=200)),
                ('description2', models.TextField()),
                ('inuse2', models.BooleanField(default=False)),
                ('project3', models.TextField()),
                ('title3', models.CharField(max_length=200)),
                ('description3', models.TextField()),
                ('inuse3', models.BooleanField(default=False)),
                ('project4', models.TextField()),
                ('title4', models.CharField(max_length=200)),
                ('description4', models.TextField()),
                ('inuse4', models.BooleanField(default=False)),
                ('project5', models.TextField()),
                ('title5', models.CharField(max_length=200)),
                ('description5', models.TextField()),
                ('inuse5', models.BooleanField(default=False)),
                ('project6', models.TextField()),
                ('title6', models.CharField(max_length=200)),
                ('inuse6', models.BooleanField(default=False)),
                ('project7', models.TextField()),
                ('title7', models.CharField(max_length=200)),
                ('inuse7', models.BooleanField(default=False)),
                ('project8', models.TextField()),
                ('title8', models.CharField(max_length=200)),
                ('inuse8', models.BooleanField(default=False)),
                ('project9', models.TextField()),
                ('title9', models.CharField(max_length=200)),
                ('inuse9', models.BooleanField(default=False)),
                ('project10', models.TextField()),
                ('title10', models.CharField(max_length=200)),
                ('inuse10', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='structuredproject',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 24, 17, 46, 19, 638011), verbose_name='date published'),
        ),
    ]
