# Generated by Django 2.1.5 on 2020-03-24 19:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20200324_1746'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('code', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='PersonalProjects',
        ),
        migrations.AlterField(
            model_name='structuredproject',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 24, 19, 47, 8, 163087), verbose_name='date published'),
        ),
    ]
