# Generated by Django 2.1.5 on 2020-03-24 20:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20200324_1954'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalproject',
            name='title',
            field=models.CharField(default='Circle Drive', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='structuredproject',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 24, 20, 0, 46, 366739), verbose_name='date published'),
        ),
    ]
