# Generated by Django 2.1.5 on 2020-03-26 12:59

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20200324_2001'),
    ]

    operations = [
        migrations.AddField(
            model_name='structuredproject',
            name='slug',
            field=models.CharField(default='1', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='personalproject',
            name='username',
            field=models.ForeignKey(default='pdmcguckian', on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='structuredproject',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 26, 12, 59, 27, 62946), verbose_name='date published'),
        ),
    ]
