# Generated by Django 2.1.5 on 2020-03-26 13:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20200326_1259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='structuredproject',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 26, 13, 49, 19, 415350), verbose_name='date published'),
        ),
    ]
