# Generated by Django 2.1.5 on 2020-03-26 14:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20200326_1427'),
    ]

    operations = [
        migrations.RenameField(
            model_name='personalproject',
            old_name='username',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='structuredproject',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 26, 14, 35, 29, 434079), verbose_name='date published'),
        ),
    ]
