# Generated by Django 2.1.5 on 2020-03-27 16:11

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_auto_20200326_1739'),
    ]

    operations = [
        migrations.CreateModel(
            name='StructuredProjectContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step', models.IntegerField()),
                ('video_link', models.CharField(max_length=200)),
                ('instructions', models.TextField()),
                ('default_code', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='personalproject',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='structuredproject',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 27, 16, 11, 46, 977170), verbose_name='date published'),
        ),
        migrations.AddField(
            model_name='structuredprojectcontent',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.StructuredProject'),
        ),
    ]
