# Generated by Django 2.1.5 on 2020-03-27 16:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_auto_20200327_1611'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personalproject',
            name='user',
        ),
        migrations.AddField(
            model_name='personalproject',
            name='slug',
            field=models.CharField(default='look-me-in-the-eyes', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='structuredproject',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 27, 16, 26, 35, 719814), verbose_name='date published'),
        ),
    ]
