# Generated by Django 2.1.5 on 2020-03-27 16:30

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0022_auto_20200327_1627'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personalproject',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='structuredprojectcontent',
            name='project',
        ),
        migrations.AddField(
            model_name='personalproject',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='structuredproject',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 27, 16, 30, 52, 241674), verbose_name='date published'),
        ),
    ]
