# Generated by Django 2.1.5 on 2020-03-27 17:04

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0024_auto_20200327_1632'),
    ]

    operations = [
        migrations.CreateModel(
            name='StructuredProjectCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='structuredproject',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 27, 17, 4, 47, 343052), verbose_name='date published'),
        ),
        migrations.AddField(
            model_name='structuredprojectcode',
            name='slug',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.StructuredProject'),
        ),
        migrations.AddField(
            model_name='structuredprojectcode',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
