# Generated by Django 2.1.5 on 2020-03-27 17:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_auto_20200327_1704'),
    ]

    operations = [
        migrations.RenameField(
            model_name='structuredprojectcode',
            old_name='slug',
            new_name='project',
        ),
        migrations.AlterField(
            model_name='structuredproject',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 27, 17, 8, 5, 755457), verbose_name='date published'),
        ),
    ]
