# Generated by Django 2.1.5 on 2020-03-27 17:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_auto_20200327_1708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='structuredproject',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 27, 17, 9, 14, 928123), verbose_name='date published'),
        ),
    ]
