# Generated by Django 3.0.4 on 2020-03-28 16:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_auto_20200327_1709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='structuredproject',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 28, 16, 24, 29, 990428), verbose_name='date published'),
        ),
    ]
