# Generated by Django 3.0.4 on 2020-03-28 17:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_auto_20200328_1741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='structuredproject',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 28, 17, 47, 7, 782129), verbose_name='date published'),
        ),
    ]
