# Generated by Django 3.0.4 on 2020-03-28 21:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0031_auto_20200328_1747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='structuredproject',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 28, 21, 15, 39, 941348), verbose_name='date published'),
        ),
    ]
